/**
 * Emits supabase/seed.sql from src/data/*.ts so the DB and the local fallback
 * never drift.  Run: npm run seed:sql
 */
import fs from "node:fs";
import path from "node:path";
import { branches, colleges, programs, regulations, subjects } from "../src/data/academic";
import { resources } from "../src/data/resources";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(",")}]::text[]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
// deterministic uuid from slug so re-runs are idempotent
const uuid = (s: string) => `uuid_generate_v5('6ba7b810-9dad-11d1-80b4-00c04fd430c8', ${q(s)})`;

const out: string[] = [
  "-- generated by web/scripts/gen-seed-sql.ts — do not edit by hand",
  'create extension if not exists "uuid-ossp";',
  "begin;",
];

for (const c of colleges)
  out.push(
    `insert into colleges (id,slug,name,short_name,type,is_autonomous,follows_university_syllabus,website) values (${uuid(c.id)},${q(c.slug)},${q(c.name)},${q(c.short_name)},${q(c.type)},${c.is_autonomous},${c.follows_university_syllabus},${q(c.website)}) on conflict (slug) do nothing;`,
  );
for (const r of regulations)
  out.push(
    `insert into regulations (id,slug,name,owner_college_id,applicable_from_year,source_url) values (${uuid(r.id)},${q(r.slug)},${q(r.name)},${uuid(r.owner_college_id)},${r.applicable_from_year},${q(r.source_url)}) on conflict do nothing;`,
  );
for (const p of programs)
  out.push(`insert into programs (id,slug,name,duration_years) values (${uuid(p.id)},${q(p.slug)},${q(p.name)},${p.duration_years}) on conflict (slug) do nothing;`);
for (const b of branches)
  out.push(
    `insert into branches (id,slug,code,name,program_id) values (${uuid(b.id)},${q(b.slug)},${q(b.code)},${q(b.name)},${uuid(b.program_id)}) on conflict do nothing;`,
  );
for (const s of subjects)
  out.push(
    `insert into subjects (id,slug,code,name,short_name,regulation_id,branch_id,year,semester,kind,credits,elective_group,aliases) values (${uuid(s.id)},${q(s.slug)},${q(s.code)},${q(s.name)},${q(s.short_name)},${uuid(s.regulation_id)},${uuid(s.branch_id)},${s.year},${s.semester},${q(s.kind)},${q(s.credits)},${q(s.elective_group)},${q(s.aliases)}) on conflict (slug) do update set code=excluded.code,name=excluded.name,short_name=excluded.short_name,credits=excluded.credits,elective_group=excluded.elective_group,aliases=excluded.aliases;`,
  );
for (const r of resources)
  out.push(
    `insert into resources (title,url,type,source,subject_id,unit_number,description,language,status,score) values (${q(r.title)},${q(r.url)},${q(r.type)},${q(r.source)},${uuid(r.subject_id)},${q(r.unit_number)},${q(r.description)},${q(r.language)},${q(r.status)},${r.score}) on conflict (subject_id,url_hash) do nothing;`,
  );
out.push("commit;");

const dest = path.resolve(__dirname, "../../supabase/seed.sql");
fs.writeFileSync(dest, out.join("\n") + "\n");
console.log(`wrote ${dest} — ${subjects.length} subjects, ${resources.length} resources`);
